packages:
  - name: verification
    functions:
      - name: persona-webhook
        runtime: nodejs:default
        web: true
        environment:
          PERSONA_WEBHOOK_SECRET: ${PERSONA_WEBHOOK_SECRET}
          INTERNAL_API_KEY: ${GATEWAY_MASTER_KEY}
          API_GATEWAY_URL: ${API_GATEWAY_URL}
